In [1]:
#numpy >> numerical python
#in 2005 by Travis Oliphnat

In [2]:
#before numpy python donot have any library for mathmathetical calculation
#so there was need of libary on python which  much focused on mathmatical calculation

In [3]:
#importing
import numpy as np


In [4]:
np.__version__


'1.26.4'

In [5]:
print(np.__doc__)   #to see numpy doc


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [6]:
#we know list


In [7]:
lis= [1, 2, 3, "sourav", 3+5j, True, 1.2]
#in it we can put any type of data


In [8]:
type(lis)

list

In [9]:
#Numpy stores data in array

#AN array is a container used to store the data of same data type such as integer, float or character
#array is the container that strore only homgenous data

#where in list we can store any type of data

In [10]:
#why numpy:

#1 >>computation is fast>> because numpy store data in the form of array and store only of same data type

#array is fast as compare to list as it is continous memory location

#in list this is not the case

#2>> mathmatical computation

In [11]:
l = [1, 2, 3, 4, 5]  #this is an list
l

[1, 2, 3, 4, 5]

In [12]:
#to convert this list into array>>
arr= np.array(l)

In [13]:
arr

array([1, 2, 3, 4, 5])

In [14]:
#array([1, 2, 3, 4, 5]) >> this mean all these are homogenous data >> means all are intgers


In [15]:
l =[1, 2,3, 4, 5.1]
arr= np.array(l)

In [16]:
arr

array([1. , 2. , 3. , 4. , 5.1])

In [17]:
#now we can see all the element get converted to float type

In [18]:
l =[1, 2,3, 4, 5.1, "Ajay"]
arr= np.array(l)

In [19]:
arr

array(['1', '2', '3', '4', '5.1', 'Ajay'], dtype='<U32')

In [20]:
#now we can see all get converted to string

In [21]:
#it will never happen that one data is string and other are others 

In [22]:
#for this the type element get converted to maintain homogenity

In [23]:
#so in this way array store homogenous data and this is the reason it is faster as compare to list

In [24]:
type(arr)

numpy.ndarray

In [25]:
#here nd stand for n dimensions

In [26]:
#to know what is the dimension of array
arr.ndim

1

In [58]:
#to make 2d array>>

arr1 = np.array([[1,2,3], [4,5,6]])  #here list inside a list
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr1 = np.array([[1,2,3], [4,5,6], [7, 8, 9]])  #here list inside a list
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
#now we can see it is of two dimension
# there is square bracket two in no. [[ , so, it represent 2 dimensional array

In [29]:
type(arr1)

numpy.ndarray

In [30]:
arr1.ndim

2

In [31]:
#

## Matrix in Numpy


In [32]:
#matrix is the way to represent data in vector form

In [33]:
#matrix is a spelized array.
#it is alwyas in 2D

#we cannot make 3D matrix

In [34]:
max1= np.matrix([1,2,3,4])  #in this np.matrix()  we can pass any no. whatever we want to keep as a matrix

In [35]:
#we need matrix since some calculation for matrix is different
#for example matrix multiplication, inverse of the matrix

#sp for those calc. we have this spelized array called matrix

In [36]:
max1

matrix([[1, 2, 3, 4]])

In [37]:
type(max1)

numpy.matrix

In [38]:
##we cannot make 3D matrix
#let's try to build

np.matrix([[[1,2], [3,4], [5,6]]])

ValueError: matrix must be 2-dimensional

In [ ]:
#hence matrix must be always 2D

In [ ]:
max1 = np.matrix([[1,2], [2,3]])

In [ ]:
max1

In [39]:
#A matrix is a specialized 2-D array that retains its 2-D nature through operations.
#It has certain special operators, such as * (matrix multiplication) and ** (matrix power).

In [40]:
#one way to convert something is np.array()

#there are another way to convert as array>>

In [41]:
#More way to convert array

l= [1, 2, 3, 4]
np.asarray(l)  #it will also convert which is  an array or it sub-class to an array

array([1, 2, 3, 4])

In [42]:
#if something is already an array or it sub-class it will also convert it in array>>


In [43]:
max1= np.matrix([1,2,3,4]) 

In [44]:
max1

matrix([[1, 2, 3, 4]])

In [45]:
#As matrix already a Array sub-class

#now if we putr max1 in np.asarray()

In [46]:
np.asarray(max1)

array([[1, 2, 3, 4]])

In [ ]:
#so here we see if something is alreay a sub class 0r array , it will also convert it

In [47]:
#there is on more another way to convert it into array>>

#np.asanyarray 


#now for np.asanyarray() only convert only those array which is not an array and 
#which already a sub class of an array it will not convert it

In [49]:
np.asanyarray([1, 2, 3])

array([1, 2, 3])

In [50]:
#it is converting which is not an array

In [51]:
max1


matrix([[1, 2, 3, 4]])

In [52]:
#now if we pass this max1 which is not an array it will convert it

np.asanyarray(max1)  #convert the input to an ndarray, but pass ndarray subclasses through.

matrix([[1, 2, 3, 4]])

In [53]:
#now we can see it is not get converted and remains only matrix

In [54]:
#NOW FOR A TUPLE TO CONVERT IT INTO AN ARRAY>>

In [55]:
#tuple to an array
t = ([1, 2, 3], [4, 5, 6]) #tuple to array

In [56]:
type(t)

tuple

In [57]:
np.array(t)  #now tuple get converted to an array

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
#for list>>

l = [1, 2, 3, 4, 5]
arr = np.array(l)

In [62]:
arr

array([1, 2, 3, 4, 5])

In [63]:
#TO ACCESS AN INDEX OF AN ARRAY>>

In [64]:
#to access 1st index>>
arr[0]

1

In [65]:
#to change this value
arr[0] = 500

In [66]:
arr

array([500,   2,   3,   4,   5])

In [67]:
#SO ARRAY IS MUTABLE

## CONCEPT OF DEEP COPY AND SHALLOW COPY

In [68]:
arr

array([500,   2,   3,   4,   5])

In [69]:
a = arr

In [70]:
a

array([500,   2,   3,   4,   5])

In [71]:
#now here we are changing value in array 'arr'>>

arr[0] = 1000

In [72]:
#here we have make changes to arr not a

In [73]:
arr


array([1000,    2,    3,    4,    5])

In [74]:
a

array([1000,    2,    3,    4,    5])

In [75]:
#now we can see here we have not make any changes to "a'' then also a changes

In [77]:
#SO THIS IS THE CONCEPT OF SHALLOW COPY>>

#change in array also let to change in a

In [78]:
#DEEP COPY>>

In [79]:
a = arr.copy()

In [80]:
a

array([1000,    2,    3,    4,    5])

In [81]:
arr

array([1000,    2,    3,    4,    5])

In [82]:
#now here we formed deep copy have diff memory reference

In [83]:
arr[0] = 2000

In [84]:
arr

array([2000,    2,    3,    4,    5])

In [85]:
a

array([1000,    2,    3,    4,    5])

In [87]:
#now here we can see on changing "arr" , "a" is not changing as both have diff. memory refernce

In [88]:
#SO to create an array>> np.array, np.asarray, np.asanyarray(in this what that is in array or array subclass not changes and remains as it is)

In [89]:

#OTHER MULTIPLE WAYS TO GENERATE AN ARRAY>>

In [94]:
arr1 = np.fromfunction(lambda i, j : i==j, (3,3))   #Construct an array by executing a function over each coordinate.

#it tells where i==j give me true and construct an array of (3,3)

In [95]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [96]:
arr1.ndim

2

In [98]:
arr1.shape  #to now rows and column

(3, 3)

In [100]:
arr1.size   #no. of elements

9

In [101]:
arr2 = np.fromfunction(lambda i, j : i*j, (3,3)) 

In [102]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [103]:
#ARRAY FRom iterable>>

In [105]:
for i in range(5):
    print(i)

0
1
2
3
4


In [106]:
#same thing in list comprension>>

[i for i in range(5)]

[0, 1, 2, 3, 4]

In [107]:
#now to convert this to an array>>



In [108]:
# we can also convert this [i for i in range(5)] into tuple, it doesnot matter it is list or tuple

In [109]:
(i for i in range(5))

<generator object <genexpr> at 0x000002C6BAB2FF40>

In [111]:
#now
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [113]:
#so it doenot matter that it is in list or tuple , what matter is that it genretor object to be made

(i for i in range(5)) #this is an iterable object

<generator object <genexpr> at 0x000002C6BD612EC0>

In [114]:
iterable = (i for i in range(5))

In [115]:
#NOW to convert this into array>>

np.fromiter(iterable, int)  #Create a new 1-dimensional array from an iterable object. here iter>> iterable

array([0, 1, 2, 3, 4])

In [116]:
#array creted from using string>>

np.fromstring('22 23 24', sep=" ")  #in sep>> seprator we have to give what is the seprator in between '22 23 24'

array([22., 23., 24.])

In [122]:
#this seprator can be anything>>

#for strings you have to use split
string1 = string.split(',')
np.array(string1)

array(['Ajay', 'Bijay', 'Sanjay'], dtype='<U6')

In [123]:
string1

['Ajay', 'Bijay', 'Sanjay']

In [124]:
np.fromstring('22 23 24', sep=" ")  #this method work only for integer  #so values should be numeric 
#it should have array of data in only in string format where values should be numeric

array([22., 23., 24.])

In [125]:
np.fromstring('22,23,24', sep=",")

array([22., 23., 24.])

In [126]:
np.fromstring('22/23/24', sep="/")

array([22., 23., 24.])

In [ ]:
#other methods of numpy>>

In [127]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [128]:
#but if we directly write
range(10)

range(0, 10)

In [129]:
#we will not get value directly

In [130]:
#in numpy we have simlar function arange>> in that case we get value directly

In [ ]:
#other methods of numpy>> to generate sequence if nos

In [131]:
np.arange(1, 10, 0.1)    #1> start from where #10> to which have to go  #0.1>with step of

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [132]:


#

In [134]:
#now if we want to generate a number if it is equally spaced>>

np.linspace(1, 5, 10)  #retun  evenly spaced number over a specified interval.
#(1, 5, 10)>> it says generte me a 10 no.s evenly spaced between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [137]:
np.logspace(1, 5, 10)  #Return numbers spaced evenly on a log scale.  #base is 10



array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [138]:


'''np.logspace(
    start,
    stop,
    num=50,
    endpoint=True,
    base=10.0,
    dtype=None,
    axis=0,'''

'np.logspace(\n    start,\n    stop,\n    num=50,\n    endpoint=True,\n    base=10.0,\n    dtype=None,\n    axis=0,'

In [139]:
#10 evenly space no. with base 2
np.logspace(1, 5, 10, base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])