In [4]:
import numpy as np

In [5]:
a = np.zeros(5)  #Return a new array of given shape and type, filled with zeros.


In [6]:
a

array([0., 0., 0., 0., 0.])

In [7]:
a.ndim

1

In [8]:
b  = np.zeros((3,4))

In [9]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
b.ndim

2

In [11]:
#for all the values to be 1

c = np.ones((3,4))  #Return a new array of given shape and type, filled with ones.


In [12]:
c.ndim

2

In [13]:
#if we want to have every element to be 2>> there is no any function for it

np.twos(5)  #doesnot exist in numpy

AttributeError: module 'numpy' has no attribute 'twos'

In [14]:
#so, in that case we have to actually difine numpy array and give all element to 2

In [15]:
np.array([2,2,2])

array([2, 2, 2])

In [16]:
np.array([[2,2,2], [2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [17]:
arr= np.zeros((3,4))

In [18]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
arr.ndim

2

In [20]:
#but we want to of 3 dimension

In [21]:
# 3 dimensional array>>

In [22]:

#when ever we put (3,4) >> it means 3 rows and 4 column

In [23]:
np.zeros((3,4))  #it is 2d array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
#but
np.zeros(1)  #this is 1 dimensional

array([0.])

In [25]:
arr= np.zeros((3,4))

In [26]:
arr.ndim

2

In [27]:
#now we want this array should be 3 dimensional>>


In [28]:
arr = np.zeros((1, 3, 4))  #this 3, 4>> means 3 rows and 4 column and one extra outer dimension 1

In [29]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [30]:
#now we can see 3 square bracket it means now it 3 dimension array

In [31]:
#we can not able to visulize it

In [32]:
arr.ndim

3

In [33]:
#now it cleary 3 d 

In [34]:
#if want to of more dimension>>
arr =  np.zeros((1, 1, 3, 4))  #we will increase one extra outer dimension 1

In [35]:
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [36]:
#now we can see 4 square bracket so it is of 4 dimensions

In [37]:
arr.ndim

4

In [38]:
#now increasing 1 more dimension>>
arr =  np.zeros((1, 1, 1, 3, 4)) 

In [39]:
arr

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]]])

In [40]:
#now we can see it has 5 dimension as it have 5 square bracket 

In [41]:
arr.ndim

5

In [42]:
#SOME OTHER METHOD TO GENERATE AN ARRAY>>

In [43]:
arr = np.ones((3,4))

In [44]:
arr.ndim

2

In [45]:
arr.shape

(3, 4)

In [46]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
#if we want to add every element of this array with 5>>

arr + 5  #indexwise it will add

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [48]:
arr * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [49]:
arr -1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.eye(3)   #Return a 2-D array with ones on the diagonal and zeros elsewhere.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
#it is very useful in calculating inverse of a matrix

In [52]:
np.eye(3, dtype = int)  #if want elements in int

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [53]:
np.empty((3,4))  #Return a new array of given shape and type, without initializing entries.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
np.empty((3,6)) 

array([[3.56043053e-307, 1.60219306e-306, 7.56571288e-307,
        7.56587584e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.42417221e-306, 9.34605037e-307],
       [6.23059726e-307, 1.24612353e-306, 8.90092016e-307,
        1.86919378e-306, 1.42410974e-306, 9.34608431e-307]])

In [55]:
np.empty((3,6)) 

array([[3.56043053e-307, 1.60219306e-306, 7.56571288e-307,
        7.56587584e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.42417221e-306, 9.34605037e-307],
       [6.23059726e-307, 1.24612353e-306, 8.90092016e-307,
        1.86919378e-306, 1.42410974e-306, 9.34608431e-307]])

In [56]:
#so it will give some random elements

In [57]:
#optional>>

#before some time if we have to genrate random we have to import random module
import random
random.choice((1,2,3,4,5))  #it will give any random from (1,2,3,4,5)

1

In [58]:
random.choice((1,2,3,4,5)) 

4

In [59]:
random.choice((1,2,3,4,5)) 

5

In [60]:
random.choice([1,2, 3,4, 5])

4

In [61]:
#random character from a string>>
random.choice('Ajay')

'a'

In [62]:
#random no. from a range>>
random.randrange(1, 10)  #1 to 10

3

In [63]:
#if we want simply random no.

In [64]:
random.random() #a random no. is genrated between 0(included) and 1(excluded)

0.4753586432273226

In [65]:
#if we want  to suffle no.>>

lis = [1, 2, 3, 4 , 5]
lis

[1, 2, 3, 4, 5]

In [67]:
random.shuffle(lis)  #it will be randomly resuffle

In [68]:
lis

[5, 1, 2, 3, 4]

In [69]:
#now we can see lis value is resuffled randomly

In [70]:
#if want to genrate some no. that is uniformly distributed>>

In [72]:
random.uniform(7,14)

7.6040538276306835

In [74]:
#RANDOM NUMBERS RELATED CONCEPTS IN NUMPY>>

In [75]:
#in numpy also some random packages included>>

In [76]:
#to generate random no using numpy package



In [77]:
np.random #when we use it in backed it is same random module but in numpy it is integated

<module 'numpy.random' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\numpy\\random\\__init__.py'>

In [78]:
np.random.random_sample()  #Return random floats in the half-open interval [0.0, 1.0).

0.8189670188568633

In [81]:
np.random.random_sample((5))  #wwe get randomly genrated array in one dimension having 5 dimension

array([0.81510593, 0.39067905, 0.02549467, 0.18158619, 0.67588479])

In [82]:
np.random.random_sample((5, )) 

array([0.53552188, 0.93985453, 0.21735326, 0.80076131, 0.24331717])

In [83]:
#if we want to generate only one element array

In [84]:
np.random.rand(1)  #Random values in a given shape.

array([0.15060712])

In [85]:
np.random.rand(5) 

array([0.85901491, 0.56714633, 0.71555732, 0.15973109, 0.84149573])

In [87]:
#if we want to dimensional value>>
np.random.rand(2,3)

array([[0.74657706, 0.46079972, 0.2892725 ],
       [0.82553883, 0.96032847, 0.80302166]])

In [89]:
#now suppose we want a number that come from a specific type of distribution which a random distribution>>

np.random.randn(2,3)

array([[ 0.45295285, -0.92356303,  0.6787825 ],
       [-0.61794068,  0.22696493,  0.23467059]])

In [90]:
#thsese no. coming from normal distribution

In [91]:

#it is genrating a float no.

In [93]:
#but if we want to genrate some random integer no.>>
arr =np.random.randint(1, 5, size = (3,4)) # this array is genrate in size (3,4) from no. between 1 and 5

In [94]:
arr

array([[1, 4, 2, 1],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [95]:
arr.ndim

2

In [96]:
arr.shape

(3, 4)

In [97]:
arr.size

12

In [98]:
arr

array([[1, 4, 2, 1],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [99]:
#now if want to change the shape of this array>>

In [101]:
#reshaping the array>>

arr1 = arr.reshape(2,6)  #reshaping arr with 2 rows and 6 column
arr1

array([[1, 4, 2, 1, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [102]:
#now we can see same array is reshaped

In [103]:
arr1.shape

(2, 6)

In [104]:
arr1.size 

12

In [105]:
#array size not changed

#always reshape parameter should be multiplication of orginal array size

In [106]:
arr1

array([[1, 4, 2, 1, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [107]:
arr

array([[1, 4, 2, 1],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [108]:
arr.size

12

In [109]:
arr.reshape(2,6) #parameter should be multiplication of orginal array size

array([[1, 4, 2, 1, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [112]:
arr.reshape(2,5) #not work

ValueError: cannot reshape array of size 12 into shape (2,5)

In [113]:
arr.reshape(1,12) #work

array([[1, 4, 2, 1, 3, 3, 3, 3, 3, 3, 3, 3]])

In [114]:
arr.reshape(12,1) #work

array([[1],
       [4],
       [2],
       [1],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3]])

In [115]:
arr.reshape(3,4) #work

array([[1, 4, 2, 1],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [116]:
arr.reshape(4,3) #work

array([[1, 4, 2],
       [1, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [117]:
#CASE>> whwn we dont know in reshape what should be the column count/column part

In [118]:
#suppose we want 4 rows so we write rows as 4 
#and column as -1 it will automatically underatand amount of column

In [119]:
arr.reshape(4, -1)

array([[1, 4, 2],
       [1, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [120]:
#Now if we dont knew column >>
arr.reshape(2, -1)

array([[1, 4, 2, 1, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [121]:
#insted of -1 we can put any negative no.
#Now if we dont knew column >>
arr.reshape(2, -1000)

array([[1, 4, 2, 1, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [123]:
#Now if we dont knew row and knew column>>
arr1 = arr.reshape( -1,2)

array([[1, 4],
       [2, 1],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [124]:
arr1.size

12

In [126]:
arr.reshape(12, 1) 

array([[1],
       [4],
       [2],
       [1],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3]])

In [129]:
#now suppose if we don't knew orginal array and we want to see that >>
arr.reshape(12, 1).base

array([[1, 4, 2, 1],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [130]:
#WE CAN ALSO RESHAPE IT INTO ANY DIMENSION>>


In [131]:
arr.reshape(2,2,3)  #means 2*3 2d matrix 2 times

array([[[1, 4, 2],
        [1, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3]]])

In [132]:
arr.reshape(1, 2, 2, 3)  #this means 2 rows 3 column repeated 2 times and 1 extra outer  4th dimension

array([[[[1, 4, 2],
         [1, 3, 3]],

        [[3, 3, 3],
         [3, 3, 3]]]])

In [134]:
arr.reshape(1, 2, 2, 3).ndim

4

In [135]:
arr.reshape(4, 3, 1) #so this mean 3*1 repeted 4 times in 3rd dimension

array([[[1],
        [4],
        [2]],

       [[1],
        [3],
        [3]],

       [[3],
        [3],
        [3]],

       [[3],
        [3],
        [3]]])

In [136]:
#CONDITIONS ON ARRAY>>



In [137]:
arr1 = np.random.randint(1, 10, (5,6)) #Return random integers from `low` (inclusive) to `high` (exclusive).

In [138]:
arr1

array([[2, 7, 2, 3, 1, 4],
       [7, 8, 6, 2, 8, 3],
       [4, 3, 3, 2, 5, 7],
       [4, 3, 9, 8, 7, 4],
       [7, 9, 1, 5, 4, 5]])

In [139]:
arr1.shape

(5, 6)

In [140]:
arr1.ndim

2

In [141]:
arr1.size

30

In [142]:
#now if want all the element pass with condition

In [143]:
arr1 > 3

array([[False,  True, False, False, False,  True],
       [ True,  True,  True, False,  True, False],
       [ True, False, False, False,  True,  True],
       [ True, False,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True]])

In [144]:
#where condition is statisfying is true and all other are false

In [145]:
#now if want arr1 > 3

arr1[arr1>3]

array([7, 4, 7, 8, 6, 8, 4, 5, 7, 4, 9, 8, 7, 4, 7, 9, 5, 4, 5])

In [147]:
#for less than
arr1[arr1<3]

array([2, 2, 1, 2, 2, 1])

In [152]:
#TO ACCESS ELEMENTS IN THE ARRAY

In [153]:
#if we want its 0th row>>
arr1[0]

array([2, 7, 2, 3, 1, 4])

In [154]:
arr1[1]

array([7, 8, 6, 2, 8, 3])

In [155]:
#now if we want 1st element of 1st row
arr1[1][1]

8

In [156]:
arr1[1][0]

7

In [157]:
arr1

array([[2, 7, 2, 3, 1, 4],
       [7, 8, 6, 2, 8, 3],
       [4, 3, 3, 2, 5, 7],
       [4, 3, 9, 8, 7, 4],
       [7, 9, 1, 5, 4, 5]])

In [158]:
#now if want from 0th row to 1st row in continuation

In [161]:
arr1[0:2] #simple slicing

array([[2, 7, 2, 3, 1, 4],
       [7, 8, 6, 2, 8, 3]])

In [162]:
arr1[0:3]  #0th row , 1st row and 2nd row

array([[2, 7, 2, 3, 1, 4],
       [7, 8, 6, 2, 8, 3],
       [4, 3, 3, 2, 5, 7]])

In [163]:
#now in this arr1[0:3] we want 0th coloum and 2nd column
arr1[0:3, [0,2]]  #0th to 2nd row and 0th and 2nd column

array([[2, 2],
       [7, 6],
       [4, 3]])

In [165]:
#slicing on both row and column in continutiuon>>

arr1[0:3, 1:3]

array([[7, 2],
       [8, 6],
       [3, 3]])

In [166]:
arr1[0:2, [0,1]]

array([[2, 7],
       [7, 8]])

In [168]:
arr1[0 , [1,3]] #0th row and column ffrom 1 and 3rd

array([7, 3])

In [169]:
arr1[2:4, [0,3]]

array([[4, 2],
       [4, 8]])

In [170]:
#if we want only rows>>
arr1[2:5]  #rows from 2nd to 5th 

array([[4, 3, 3, 2, 5, 7],
       [4, 3, 9, 8, 7, 4],
       [7, 9, 1, 5, 4, 5]])

In [172]:
arr1[2:5, 0:2] 

array([[4, 3],
       [4, 3],
       [7, 9]])

In [173]:
arr1[0, [1, 3]]

array([7, 3])

In [ ]:
#MATHMATICAL OPERATIONS ON TWO ARRAYS>>

In [174]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [175]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 1]])

In [176]:
arr2

array([[2, 2, 1],
       [1, 2, 1],
       [1, 1, 1]])

In [177]:
#to add:
arr1 + arr2

array([[4, 3, 3],
       [3, 4, 3],
       [2, 2, 2]])

In [178]:
arr1 - arr2

array([[ 0, -1,  1],
       [ 1,  0,  1],
       [ 0,  0,  0]])

In [179]:
#these are inex wise addition and subtraction of element

In [180]:
arr1 * arr2  #index wise multiplication

array([[4, 2, 2],
       [2, 4, 2],
       [1, 1, 1]])

In [183]:
arr1, arr2

(array([[2, 1, 2],
        [2, 2, 2],
        [1, 1, 1]]),
 array([[2, 2, 1],
        [1, 2, 1],
        [1, 1, 1]]))

In [184]:
#divide element wise
arr1/arr2 #index wise division

array([[1. , 0.5, 2. ],
       [2. , 1. , 2. ],
       [1. , 1. , 1. ]])

In [185]:

#there is one more concept that is called as matrix or . matrix multiplication

In [187]:
#MATRIX MULTIPLICTION >> different from index wise multiplication

arr1 @ arr2 #1st way to do matrix multiplication

array([[ 7,  8,  5],
       [ 8, 10,  6],
       [ 4,  5,  3]])

In [188]:
np.dot(arr1, arr2) #2st way to do matrix multiplication

array([[ 7,  8,  5],
       [ 8, 10,  6],
       [ 4,  5,  3]])

In [189]:
#if we divide by 0>>
arr1/0

C:\Users\ASUS\AppData\Local\Temp\ipykernel_9948\3039078041.py:2: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [190]:
4/0

ZeroDivisionError: division by zero

In [191]:
#in python it will give error but in numpy it is inf, inf....

In [ ]:
#BROADCASTING

In [192]:
arr = np.zeros((3,4))

In [193]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [194]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [195]:
#interanlly waht will happen of same size (3,4) a matrix of 5 is created and then add each element , element wise

In [196]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [197]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [198]:
a = np.array([1, 2, 3, 4])

In [199]:
a

array([1, 2, 3, 4])

In [200]:
a.ndim

1

In [203]:
#arr this is our array and when we do arr + a what will happens?

# array([[0., 0., 0., 0.],
#        [0., 0., 0., 0.],
#        [0., 0., 0., 0.]])  these orginial elements of all the elements ([1, 2, 3, 4]) will be broadcasted for each of these rows

In [204]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [205]:
#([1, 2, 3, 4]) will be broadcasted 3 times in 3 matrix with rest of element being 0 in diff - diff row every times  and then added  and we got this result

In [206]:
#CONCEPT OF TRANSPOSE>>

In [207]:
#making row >> column

In [208]:
a = np.array([1, 2, 3, 4])

In [209]:
a

array([1, 2, 3, 4])

In [210]:
#making row >> column

In [211]:
a.T

array([1, 2, 3, 4])

In [212]:
#since it is 1D we are not able to understand

In [214]:
#now if make it 2D>>
#and then make it transpose>>

a = np.array([[1, 2, 3, 4]])

In [215]:
#now its 2D
a

array([[1, 2, 3, 4]])

In [216]:
a.T  #and if we make transpose now

array([[1],
       [2],
       [3],
       [4]])

In [217]:
arr1

array([[2, 1, 2],
       [2, 2, 2],
       [1, 1, 1]])

In [218]:
arr1.T

array([[2, 2, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [221]:
arr1 = np.random.randint(1,4, (3,3))

In [222]:
arr1

array([[1, 3, 3],
       [1, 1, 1],
       [2, 2, 3]])

In [223]:
arr1.T

array([[1, 1, 2],
       [3, 1, 2],
       [3, 1, 3]])

In [224]:
#row become column here

In [225]:
#square root>>
np.sqrt(arr1)

array([[1.        , 1.73205081, 1.73205081],
       [1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.73205081]])

In [226]:
#log10
np.log10(arr1)

array([[0.        , 0.47712125, 0.47712125],
       [0.        , 0.        , 0.        ],
       [0.30103   , 0.30103   , 0.47712125]])

In [227]:
#expontial
np.exp(arr1)

array([[ 2.71828183, 20.08553692, 20.08553692],
       [ 2.71828183,  2.71828183,  2.71828183],
       [ 7.3890561 ,  7.3890561 , 20.08553692]])

In [228]:
#min of all the array
np.min(arr1)

1

In [229]:
#max of all the array
np.max(arr1)

3