In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [3]:
arr1

array([[2, 1, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [4]:
#now I want to flattend this array to one dimension>>

In [5]:
arr1.flatten()  #Return a copy of the array collapsed into one dimension.


array([2, 1, 2, 2, 1, 1, 2, 2, 1])

In [6]:
#reduces it into one dimension

In [7]:
#EXPAND THE DIMENSION


In [8]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [9]:
arr.ndim

1

In [10]:
#expand dimension.>
np.expand_dims(arr, axis =0) #on 0 axis row will expand

array([[1, 2, 3, 4]])

In [ ]:
#here since axis = 0 , so expension happen in rows

In [11]:
#now we can see it is 2D array

In [12]:
np.expand_dims(arr, axis =1)

array([[1],
       [2],
       [3],
       [4]])

In [13]:
#now we can see column wise it is expanded

In [14]:
np.expand_dims(arr, axis =1).ndim

2

In [15]:
#expand_dims >> always increses the dimensions by 1 at provided axis

In [16]:
arr = np.zeros((3,4))

In [17]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
arr.ndim

2

In [19]:
#now this can be expanded both row ways and column ways

In [22]:
np.expand_dims(arr, axis= 0) #in x axis

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
# Expand the shape of an array.

# Insert a new axis that will appear at the `axis` position in the expanded
# array shape.

In [24]:
np.expand_dims(arr, axis= 1) #in y axis

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [25]:
np.expand_dims(arr, axis= 1).ndim

3

In [26]:
a = np.array([[1], [2], [3]])

In [27]:
a

array([[1],
       [2],
       [3]])

In [29]:
a.ndim

2

In [30]:
np.squeeze(a)  #Remove axes of length one from `a`. #reduces 1 dimension

array([1, 2, 3])

In [31]:
#repeat an array
a

array([[1],
       [2],
       [3]])

In [33]:
np.repeat(a,4)   #repeat 4 times

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [34]:
arr1

array([[2, 1, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [35]:
np.repeat(arr1, 2)

array([2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1])

In [38]:
np.repeat(arr1, 2, axis=0 )  #row wise it will repeat rowwise

array([[2, 1, 2],
       [2, 1, 2],
       [2, 1, 1],
       [2, 1, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [39]:
np.repeat(arr1, 3, axis=0 ) 

array([[2, 1, 2],
       [2, 1, 2],
       [2, 1, 2],
       [2, 1, 1],
       [2, 1, 1],
       [2, 1, 1],
       [2, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [41]:
np.repeat(arr1, 3, axis=1 )  #row wise it will repeat column wise

array([[2, 2, 2, 1, 1, 1, 2, 2, 2],
       [2, 2, 2, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 1, 1, 1]])

In [44]:
a

array([[1],
       [2],
       [3]])

In [45]:
#ROLL THe matrix>>
#elements changes like>>
#1>>2 , 2>>3, 3>>1

In [46]:
np.roll(a, -2)

array([[3],
       [1],
       [2]])

In [47]:
np.roll(a, -1)

array([[2],
       [3],
       [1]])

In [48]:
#rolling in 2 dimension>>

In [51]:
c= np.array([[1,2], [3, 4], [5,6], [7,8]])

In [52]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [55]:
np.roll(c, -2)

array([[3, 4],
       [5, 6],
       [7, 8],
       [1, 2]])

In [56]:
#rotate in +ve direction
np.roll(c, 2)

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [57]:
#rolling on axis
np.roll(c, 2, axis=0)

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [58]:
#eariler there we have put 2 or -2 , the rotaion was in one was for inner dimension and one was for outher dimension

#so in always in more than one dimension we have to provide axis =0

In [59]:
#Some binaray operations>>


In [60]:
arr1

array([[2, 1, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [61]:
arr2

array([[2, 1, 1],
       [1, 2, 2],
       [1, 2, 1]])

In [62]:
#index wise 
arr1 + arr2

array([[4, 2, 3],
       [3, 3, 3],
       [3, 4, 2]])

In [63]:
arr1 - arr2

array([[ 0,  0,  1],
       [ 1, -1, -1],
       [ 1,  0,  0]])

In [64]:
arr1 * arr2

array([[4, 1, 2],
       [2, 2, 2],
       [2, 4, 1]])

In [65]:
arr1> arr2

array([[False, False,  True],
       [ True, False, False],
       [ True, False, False]])

In [66]:
#negative of all value
~arr1

array([[-3, -2, -3],
       [-3, -2, -2],
       [-3, -3, -2]])

In [67]:
#operation on numpy string array

In [68]:
d  = np.array(['pw', 'skills'])

In [69]:
d

array(['pw', 'skills'], dtype='<U6')

In [70]:
np.char.upper(d)

array(['PW', 'SKILLS'], dtype='<U6')

In [71]:
np.char.capitalize(d)

array(['Pw', 'Skills'], dtype='<U6')

In [72]:
#mathmatical functions>>


In [73]:
arr1

array([[2, 1, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [74]:
np.sin(arr1)   #sin value of array

array([[0.90929743, 0.84147098, 0.90929743],
       [0.90929743, 0.84147098, 0.84147098],
       [0.90929743, 0.90929743, 0.84147098]])

In [75]:
np.cos(arr1)

array([[-0.41614684,  0.54030231, -0.41614684],
       [-0.41614684,  0.54030231,  0.54030231],
       [-0.41614684, -0.41614684,  0.54030231]])

In [76]:
np.tan(arr1)

array([[-2.18503986,  1.55740772, -2.18503986],
       [-2.18503986,  1.55740772,  1.55740772],
       [-2.18503986, -2.18503986,  1.55740772]])

In [77]:
np.log10(arr1)

array([[0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.     ],
       [0.30103, 0.30103, 0.     ]])

In [78]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 , 2.71828183]])

In [79]:
np.power(arr1, 3)

array([[8, 1, 8],
       [8, 1, 1],
       [8, 8, 1]], dtype=int32)

In [80]:
np.mean(arr1)

1.5555555555555556

In [81]:
np.max(arr1)

2

In [82]:
np.min(arr1)

1

In [83]:
np.std(arr1)  #standard deviation

0.4969039949999533

In [84]:
np.var(arr1)  #variance

0.2469135802469136

In [85]:
arr1 - arr2

array([[ 0,  0,  1],
       [ 1, -1, -1],
       [ 1,  0,  0]])

In [87]:
#same thing can be acheived by>>
np.subtract(arr1, arr2)

array([[ 0,  0,  1],
       [ 1, -1, -1],
       [ 1,  0,  0]])

In [88]:
arr1 * arr2

array([[4, 1, 2],
       [2, 2, 2],
       [2, 4, 1]])

In [89]:
#same thing can be acheived by>>
np.multiply(arr1, arr2)

array([[4, 1, 2],
       [2, 2, 2],
       [2, 4, 1]])

In [90]:

np.mod(arr1, arr2)  #retun element wise remainder

array([[0, 0, 0],
       [0, 1, 1],
       [0, 0, 0]])

In [91]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.        ]])

In [92]:
#SORT SEARCH>>

In [93]:
e = np.array([5,6,1,2])

In [94]:
e

array([5, 6, 1, 2])

In [95]:
np.sort(e)  #it will give sorted array

array([1, 2, 5, 6])

In [96]:
f=  np.array([5, 199, 200, 6, 7, 8])

In [97]:
f

array([  5, 199, 200,   6,   7,   8])

In [98]:
np.sort(f)

array([  5,   6,   7,   8, 199, 200])

In [99]:
#now suppose we want to know that where one element is added in the array such that element remains sorted

In [100]:
#hame ek element add karna  hai issmai such that agar ham add akrte hai or to fir bhi array ki incresing or decressing order pe koi fark nhi padega


In [101]:
np.searchsorted(f, 170)  #Find indices where elements should be inserted to maintain order.

6

In [102]:
f=  np.array([5, 199, 200, 6, 7, 8, 0,  0, 0,0])

In [103]:
#to know what are non zeros elements
np.count_nonzero(f)

6

In [106]:
#value greater than 0
f[f>0]

array([  5, 199, 200,   6,   7,   8])

In [107]:
#samething can be done using >>
np.where(f>0)

(array([0, 1, 2, 3, 4, 5], dtype=int64),)

In [108]:
np.extract(f>0, f)

array([  5, 199, 200,   6,   7,   8])

In [109]:
#BIT SWAP>>

In [110]:
#we know every thing inside machine is stored in the form of 0 and 1
#so byte reprsenation of any value can be given by byte swap

In [111]:
f

array([  5, 199, 200,   6,   7,   8,   0,   0,   0,   0])

In [112]:
f.byteswap()  #Swap the bytes of the array elements

array([  83886080, -956301312, -939524096,  100663296,  117440512,
        134217728,          0,          0,          0,          0])

In [113]:
#MATRIX .>> 2d array>> numpy provide flexiblity to work with matrix

In [114]:
import numpy.matlib as nm

In [116]:
nm.zeros(5)  #with this we are able to genrate 2d matrix

matrix([[0., 0., 0., 0., 0.]])

In [117]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [118]:
#NUMPY LINER ALGEBRA>>

In [119]:
#liner aglebra>> liner algebra a barnch of mathmatics where we solve algebric condtions

In [124]:
arr1 = np.random.randint(1, 10, (3,3))
arr2 = np.random.randint(1, 10, (3,3))

In [125]:
arr1

array([[5, 3, 1],
       [9, 3, 9],
       [2, 2, 1]])

In [126]:
arr2

array([[1, 2, 4],
       [8, 7, 3],
       [5, 2, 2]])

In [127]:
#matrix mult>>
arr1 @ arr2

array([[34, 33, 31],
       [78, 57, 63],
       [23, 20, 16]])

In [128]:
#DETERMINANT>>

In [129]:
arr1

array([[5, 3, 1],
       [9, 3, 9],
       [2, 2, 1]])

In [130]:
np.linalg.det(arr1)

-36.00000000000003

In [131]:
np.linalg.inv(arr1)  #inverse of a matrix

array([[ 0.41666667,  0.02777778, -0.66666667],
       [-0.25      , -0.08333333,  1.        ],
       [-0.33333333,  0.11111111,  0.33333333]])

In [137]:
#sOLVING SYSTEM OF LINER EQUATION

In [138]:
a = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])

In [139]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [140]:
b   = np.array([16, 8, 0])

In [141]:
np.linalg.solve(a, b)  #Solve a linear matrix equation, or system of linear scalar equations.

array([2.59630607, 0.84432718, 2.21635884])

In [142]:
#so, these are value of x, y and z